#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x0d,0x7e,0x15,0x90,0x6e,0xad,
};

static const uint8_t chainparams_seed_signet[1] = {0};

static const uint8_t chainparams_seed_test[1] = {0};

static const uint8_t chainparams_seed_testnet4[1] = {0};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
